---
title: "Reference"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dverse)
library(admiralverse)
library(dplyr)
library(DT)

admiralverse <- c(
  "admiral",
  "admiraldev",
  "admiralonco",
  "admiralophtha",
  "admiralpeds",
  "admiralvaccine"
)
template <- "https://pharmaverse.github.io/{package}/reference/{topic}.html"
docs <- dverse::document_universe(admiralverse, template)

online <- docs |> filter(dverse::is_online(topic))
```

### Vignettes

Here are all the vignettes available across packages in the 'admiralverse'.
Click on each topic to read its corresponding vignette.

```{r vignettes}
vignettes <- online |> filter(type == "vignette")

vignettes |>
  distinct(topic, title, package) |>
  datatable(escape = FALSE)
```

### Datasets

Here are all the datasets. Click on each topic to read about it.

```{r datasets}
datasets <- online |> filter(keyword == "datasets")

datasets |>
  distinct(topic, title, package) |>
  datatable(escape = FALSE)
```

### Functions

Here are all the functions. Click on each topic to read about it.

```{r public}
internal <- online |> filter(keyword == "internal")

public <- online |>
  anti_join(vignettes) |>
  anti_join(datasets) |>
  anti_join(internal)

public |>
  distinct(topic, title, package) |>
  datatable(escape = FALSE)
```
